# =========================================================
# Notification Service - realtime driver push (WebSocket)
# =========================================================
spring.application.name=notification-service
server.port=8084

# ---------- Keycloak (JWT validation for /api/**) ----------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/uber-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/uber-realm/protocol/openid-connect/certs

# ---------- Actuator + Prometheus ----------
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
